//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blog: Blog;
  blogConnection: BlogConnection;
  site: Site;
  siteConnection: SiteConnection;
  home: Home;
  homeConnection: HomeConnection;
  services: Services;
  servicesConnection: ServicesConnection;
  contact: Contact;
  contactConnection: ContactConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};

export type DocumentFilter = {
  blog?: InputMaybe<BlogFilter>;
  site?: InputMaybe<SiteFilter>;
  home?: InputMaybe<HomeFilter>;
  services?: InputMaybe<ServicesFilter>;
  contact?: InputMaybe<ContactFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blog | Site | Home | Services | Contact | Folder;

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  name?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  locationNote?: Maybe<Scalars['String']['output']>;
  footerMadeWith?: Maybe<Scalars['String']['output']>;
  metaTitle?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteFilter = {
  name?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  locationNote?: InputMaybe<StringFilter>;
  footerMadeWith?: InputMaybe<StringFilter>;
  metaTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type HomeHero = {
  __typename?: 'HomeHero';
  badge?: Maybe<Scalars['String']['output']>;
  headlineLine1?: Maybe<Scalars['String']['output']>;
  headlineLine2?: Maybe<Scalars['String']['output']>;
  headlineLine3?: Maybe<Scalars['String']['output']>;
  subCopyMain?: Maybe<Scalars['String']['output']>;
  subCopyHighlight?: Maybe<Scalars['String']['output']>;
  primaryCtaLabel?: Maybe<Scalars['String']['output']>;
  secondaryCtaLabel?: Maybe<Scalars['String']['output']>;
  trustText?: Maybe<Scalars['String']['output']>;
  browserMockupUrl?: Maybe<Scalars['String']['output']>;
  scrollLabel?: Maybe<Scalars['String']['output']>;
};

export type HomeStats = {
  __typename?: 'HomeStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type HomeHomeSteps = {
  __typename?: 'HomeHomeSteps';
  num?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type HomeWhyUs = {
  __typename?: 'HomeWhyUs';
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type HomePacks = {
  __typename?: 'HomePacks';
  name?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  monthly?: Maybe<Scalars['String']['output']>;
  monthlyNote?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  accent?: Maybe<Scalars['String']['output']>;
};

export type HomeHomeCta = {
  __typename?: 'HomeHomeCta';
  headline?: Maybe<Scalars['String']['output']>;
  subCopy?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  hero?: Maybe<HomeHero>;
  stats?: Maybe<Array<Maybe<HomeStats>>>;
  homeSteps?: Maybe<Array<Maybe<HomeHomeSteps>>>;
  whyUs?: Maybe<Array<Maybe<HomeWhyUs>>>;
  packs?: Maybe<Array<Maybe<HomePacks>>>;
  homeCta?: Maybe<HomeHomeCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  headlineLine1?: InputMaybe<StringFilter>;
  headlineLine2?: InputMaybe<StringFilter>;
  headlineLine3?: InputMaybe<StringFilter>;
  subCopyMain?: InputMaybe<StringFilter>;
  subCopyHighlight?: InputMaybe<StringFilter>;
  primaryCtaLabel?: InputMaybe<StringFilter>;
  secondaryCtaLabel?: InputMaybe<StringFilter>;
  trustText?: InputMaybe<StringFilter>;
  browserMockupUrl?: InputMaybe<StringFilter>;
  scrollLabel?: InputMaybe<StringFilter>;
};

export type HomeStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HomeHomeStepsFilter = {
  num?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type HomeWhyUsFilter = {
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomePacksFilter = {
  name?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  monthly?: InputMaybe<StringFilter>;
  monthlyNote?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  accent?: InputMaybe<StringFilter>;
};

export type HomeHomeCtaFilter = {
  headline?: InputMaybe<StringFilter>;
  subCopy?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  hero?: InputMaybe<HomeHeroFilter>;
  stats?: InputMaybe<HomeStatsFilter>;
  homeSteps?: InputMaybe<HomeHomeStepsFilter>;
  whyUs?: InputMaybe<HomeWhyUsFilter>;
  packs?: InputMaybe<HomePacksFilter>;
  homeCta?: InputMaybe<HomeHomeCtaFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type ServicesHero = {
  __typename?: 'ServicesHero';
  label?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  headlineGradient?: Maybe<Scalars['String']['output']>;
  subCopy?: Maybe<Scalars['String']['output']>;
};

export type ServicesProcessSteps = {
  __typename?: 'ServicesProcessSteps';
  step?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type ServicesProcess = {
  __typename?: 'ServicesProcess';
  label?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  headlineGradient?: Maybe<Scalars['String']['output']>;
  subCopy?: Maybe<Scalars['String']['output']>;
  steps?: Maybe<Array<Maybe<ServicesProcessSteps>>>;
};

export type ServicesCta = {
  __typename?: 'ServicesCta';
  headline?: Maybe<Scalars['String']['output']>;
  subCopy?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
};

export type ServicesMeta = {
  __typename?: 'ServicesMeta';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  hero?: Maybe<ServicesHero>;
  pricingNote?: Maybe<Scalars['String']['output']>;
  process?: Maybe<ServicesProcess>;
  cta?: Maybe<ServicesCta>;
  meta?: Maybe<ServicesMeta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesHeroFilter = {
  label?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  headlineGradient?: InputMaybe<StringFilter>;
  subCopy?: InputMaybe<StringFilter>;
};

export type ServicesProcessStepsFilter = {
  step?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type ServicesProcessFilter = {
  label?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  headlineGradient?: InputMaybe<StringFilter>;
  subCopy?: InputMaybe<StringFilter>;
  steps?: InputMaybe<ServicesProcessStepsFilter>;
};

export type ServicesCtaFilter = {
  headline?: InputMaybe<StringFilter>;
  subCopy?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
};

export type ServicesMetaFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ServicesFilter = {
  hero?: InputMaybe<ServicesHeroFilter>;
  pricingNote?: InputMaybe<StringFilter>;
  process?: InputMaybe<ServicesProcessFilter>;
  cta?: InputMaybe<ServicesCtaFilter>;
  meta?: InputMaybe<ServicesMetaFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type ContactHero = {
  __typename?: 'ContactHero';
  label?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  headlineGradient?: Maybe<Scalars['String']['output']>;
  subCopy?: Maybe<Scalars['String']['output']>;
};

export type ContactFormPackOptions = {
  __typename?: 'ContactFormPackOptions';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  hero?: Maybe<ContactHero>;
  formPackOptions?: Maybe<Array<Maybe<ContactFormPackOptions>>>;
  nextSteps?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactHeroFilter = {
  label?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  headlineGradient?: InputMaybe<StringFilter>;
  subCopy?: InputMaybe<StringFilter>;
};

export type ContactFormPackOptionsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type ContactFilter = {
  hero?: InputMaybe<ContactHeroFilter>;
  formPackOptions?: InputMaybe<ContactFormPackOptionsFilter>;
  nextSteps?: InputMaybe<StringFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlog: Blog;
  createBlog: Blog;
  updateSite: Site;
  createSite: Site;
  updateHome: Home;
  createHome: Home;
  updateServices: Services;
  createServices: Services;
  updateContact: Contact;
  createContact: Contact;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};

export type DocumentUpdateMutation = {
  blog?: InputMaybe<BlogMutation>;
  site?: InputMaybe<SiteMutation>;
  home?: InputMaybe<HomeMutation>;
  services?: InputMaybe<ServicesMutation>;
  contact?: InputMaybe<ContactMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blog?: InputMaybe<BlogMutation>;
  site?: InputMaybe<SiteMutation>;
  home?: InputMaybe<HomeMutation>;
  services?: InputMaybe<ServicesMutation>;
  contact?: InputMaybe<ContactMutation>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SiteMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  locationNote?: InputMaybe<Scalars['String']['input']>;
  footerMadeWith?: InputMaybe<Scalars['String']['input']>;
  metaTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
};

export type HomeHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  headlineLine1?: InputMaybe<Scalars['String']['input']>;
  headlineLine2?: InputMaybe<Scalars['String']['input']>;
  headlineLine3?: InputMaybe<Scalars['String']['input']>;
  subCopyMain?: InputMaybe<Scalars['String']['input']>;
  subCopyHighlight?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  secondaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  trustText?: InputMaybe<Scalars['String']['input']>;
  browserMockupUrl?: InputMaybe<Scalars['String']['input']>;
  scrollLabel?: InputMaybe<Scalars['String']['input']>;
};

export type HomeStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HomeHomeStepsMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type HomeWhyUsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type HomePacksMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  monthly?: InputMaybe<Scalars['String']['input']>;
  monthlyNote?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  accent?: InputMaybe<Scalars['String']['input']>;
};

export type HomeHomeCtaMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subCopy?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  hero?: InputMaybe<HomeHeroMutation>;
  stats?: InputMaybe<Array<InputMaybe<HomeStatsMutation>>>;
  homeSteps?: InputMaybe<Array<InputMaybe<HomeHomeStepsMutation>>>;
  whyUs?: InputMaybe<Array<InputMaybe<HomeWhyUsMutation>>>;
  packs?: InputMaybe<Array<InputMaybe<HomePacksMutation>>>;
  homeCta?: InputMaybe<HomeHomeCtaMutation>;
};

export type ServicesHeroMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  headlineGradient?: InputMaybe<Scalars['String']['input']>;
  subCopy?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesProcessStepsMutation = {
  step?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesProcessMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  headlineGradient?: InputMaybe<Scalars['String']['input']>;
  subCopy?: InputMaybe<Scalars['String']['input']>;
  steps?: InputMaybe<Array<InputMaybe<ServicesProcessStepsMutation>>>;
};

export type ServicesCtaMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subCopy?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesMetaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesMutation = {
  hero?: InputMaybe<ServicesHeroMutation>;
  pricingNote?: InputMaybe<Scalars['String']['input']>;
  process?: InputMaybe<ServicesProcessMutation>;
  cta?: InputMaybe<ServicesCtaMutation>;
  meta?: InputMaybe<ServicesMetaMutation>;
};

export type ContactHeroMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  headlineGradient?: InputMaybe<Scalars['String']['input']>;
  subCopy?: InputMaybe<Scalars['String']['input']>;
};

export type ContactFormPackOptionsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  hero?: InputMaybe<ContactHeroMutation>;
  formPackOptions?: InputMaybe<Array<InputMaybe<ContactFormPackOptionsMutation>>>;
  nextSteps?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BlogPartsFragment = { __typename: 'Blog', title: string, description?: string | null, date?: string | null, category?: string | null, readTime?: string | null, body?: any | null };

export type SitePartsFragment = { __typename: 'Site', name?: string | null, tagline?: string | null, email?: string | null, location?: string | null, locationNote?: string | null, footerMadeWith?: string | null, metaTitle?: string | null, metaDescription?: string | null };

export type HomePartsFragment = { __typename: 'Home', hero?: { __typename: 'HomeHero', badge?: string | null, headlineLine1?: string | null, headlineLine2?: string | null, headlineLine3?: string | null, subCopyMain?: string | null, subCopyHighlight?: string | null, primaryCtaLabel?: string | null, secondaryCtaLabel?: string | null, trustText?: string | null, browserMockupUrl?: string | null, scrollLabel?: string | null } | null, stats?: Array<{ __typename: 'HomeStats', value?: string | null, label?: string | null } | null> | null, homeSteps?: Array<{ __typename: 'HomeHomeSteps', num?: string | null, title?: string | null, desc?: string | null } | null> | null, whyUs?: Array<{ __typename: 'HomeWhyUs', title?: string | null, desc?: string | null } | null> | null, packs?: Array<{ __typename: 'HomePacks', name?: string | null, tagline?: string | null, desc?: string | null, price?: string | null, monthly?: string | null, monthlyNote?: string | null, features?: Array<string | null> | null, featured?: boolean | null, accent?: string | null } | null> | null, homeCta?: { __typename: 'HomeHomeCta', headline?: string | null, subCopy?: string | null, ctaLabel?: string | null } | null };

export type ServicesPartsFragment = { __typename: 'Services', pricingNote?: string | null, hero?: { __typename: 'ServicesHero', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null } | null, process?: { __typename: 'ServicesProcess', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null, steps?: Array<{ __typename: 'ServicesProcessSteps', step?: string | null, title?: string | null, desc?: string | null } | null> | null } | null, cta?: { __typename: 'ServicesCta', headline?: string | null, subCopy?: string | null, ctaLabel?: string | null } | null, meta?: { __typename: 'ServicesMeta', title?: string | null, description?: string | null } | null };

export type ContactPartsFragment = { __typename: 'Contact', nextSteps?: Array<string | null> | null, hero?: { __typename: 'ContactHero', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null } | null, formPackOptions?: Array<{ __typename: 'ContactFormPackOptions', value?: string | null, label?: string | null } | null> | null };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, description?: string | null, date?: string | null, category?: string | null, readTime?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, description?: string | null, date?: string | null, category?: string | null, readTime?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, name?: string | null, tagline?: string | null, email?: string | null, location?: string | null, locationNote?: string | null, footerMadeWith?: string | null, metaTitle?: string | null, metaDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, name?: string | null, tagline?: string | null, email?: string | null, location?: string | null, locationNote?: string | null, footerMadeWith?: string | null, metaTitle?: string | null, metaDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', badge?: string | null, headlineLine1?: string | null, headlineLine2?: string | null, headlineLine3?: string | null, subCopyMain?: string | null, subCopyHighlight?: string | null, primaryCtaLabel?: string | null, secondaryCtaLabel?: string | null, trustText?: string | null, browserMockupUrl?: string | null, scrollLabel?: string | null } | null, stats?: Array<{ __typename: 'HomeStats', value?: string | null, label?: string | null } | null> | null, homeSteps?: Array<{ __typename: 'HomeHomeSteps', num?: string | null, title?: string | null, desc?: string | null } | null> | null, whyUs?: Array<{ __typename: 'HomeWhyUs', title?: string | null, desc?: string | null } | null> | null, packs?: Array<{ __typename: 'HomePacks', name?: string | null, tagline?: string | null, desc?: string | null, price?: string | null, monthly?: string | null, monthlyNote?: string | null, features?: Array<string | null> | null, featured?: boolean | null, accent?: string | null } | null> | null, homeCta?: { __typename: 'HomeHomeCta', headline?: string | null, subCopy?: string | null, ctaLabel?: string | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', badge?: string | null, headlineLine1?: string | null, headlineLine2?: string | null, headlineLine3?: string | null, subCopyMain?: string | null, subCopyHighlight?: string | null, primaryCtaLabel?: string | null, secondaryCtaLabel?: string | null, trustText?: string | null, browserMockupUrl?: string | null, scrollLabel?: string | null } | null, stats?: Array<{ __typename: 'HomeStats', value?: string | null, label?: string | null } | null> | null, homeSteps?: Array<{ __typename: 'HomeHomeSteps', num?: string | null, title?: string | null, desc?: string | null } | null> | null, whyUs?: Array<{ __typename: 'HomeWhyUs', title?: string | null, desc?: string | null } | null> | null, packs?: Array<{ __typename: 'HomePacks', name?: string | null, tagline?: string | null, desc?: string | null, price?: string | null, monthly?: string | null, monthlyNote?: string | null, features?: Array<string | null> | null, featured?: boolean | null, accent?: string | null } | null> | null, homeCta?: { __typename: 'HomeHomeCta', headline?: string | null, subCopy?: string | null, ctaLabel?: string | null } | null } | null } | null> | null } };

export type ServicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesQuery = { __typename?: 'Query', services: { __typename: 'Services', id: string, pricingNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ServicesHero', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null } | null, process?: { __typename: 'ServicesProcess', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null, steps?: Array<{ __typename: 'ServicesProcessSteps', step?: string | null, title?: string | null, desc?: string | null } | null> | null } | null, cta?: { __typename: 'ServicesCta', headline?: string | null, subCopy?: string | null, ctaLabel?: string | null } | null, meta?: { __typename: 'ServicesMeta', title?: string | null, description?: string | null } | null } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
}>;


export type ServicesConnectionQuery = { __typename?: 'Query', servicesConnection: { __typename?: 'ServicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesConnectionEdges', cursor: string, node?: { __typename: 'Services', id: string, pricingNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ServicesHero', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null } | null, process?: { __typename: 'ServicesProcess', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null, steps?: Array<{ __typename: 'ServicesProcessSteps', step?: string | null, title?: string | null, desc?: string | null } | null> | null } | null, cta?: { __typename: 'ServicesCta', headline?: string | null, subCopy?: string | null, ctaLabel?: string | null } | null, meta?: { __typename: 'ServicesMeta', title?: string | null, description?: string | null } | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, nextSteps?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ContactHero', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null } | null, formPackOptions?: Array<{ __typename: 'ContactFormPackOptions', value?: string | null, label?: string | null } | null> | null } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, nextSteps?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ContactHero', label?: string | null, headline?: string | null, headlineGradient?: string | null, subCopy?: string | null } | null, formPackOptions?: Array<{ __typename: 'ContactFormPackOptions', value?: string | null, label?: string | null } | null> | null } | null } | null> | null } };

export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  description
  date
  category
  readTime
  body
}
    `;
export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  name
  tagline
  email
  location
  locationNote
  footerMadeWith
  metaTitle
  metaDescription
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero {
    __typename
    badge
    headlineLine1
    headlineLine2
    headlineLine3
    subCopyMain
    subCopyHighlight
    primaryCtaLabel
    secondaryCtaLabel
    trustText
    browserMockupUrl
    scrollLabel
  }
  stats {
    __typename
    value
    label
  }
  homeSteps {
    __typename
    num
    title
    desc
  }
  whyUs {
    __typename
    title
    desc
  }
  packs {
    __typename
    name
    tagline
    desc
    price
    monthly
    monthlyNote
    features
    featured
    accent
  }
  homeCta {
    __typename
    headline
    subCopy
    ctaLabel
  }
}
    `;
export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  hero {
    __typename
    label
    headline
    headlineGradient
    subCopy
  }
  pricingNote
  process {
    __typename
    label
    headline
    headlineGradient
    subCopy
    steps {
      __typename
      step
      title
      desc
    }
  }
  cta {
    __typename
    headline
    subCopy
    ctaLabel
  }
  meta {
    __typename
    title
    description
  }
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  hero {
    __typename
    label
    headline
    headlineGradient
    subCopy
  }
  formPackOptions {
    __typename
    value
    label
  }
  nextSteps
}
    `;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  